version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: "Set Permission"
          command: chmod +x .circleci/teams_notification.sh
          when: on_success
      - run:
          name: "Send Notification"
          command: .circleci/teams_notification.sh
          shell: /bin/bash
          when: on_success