version: 2.1
orbs:
  ms-teams-orb: uniqueck/ms-teams-orb@0.0.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - ms-teams-orb/send-message:
          title: test
          summary: "long summary"
          text: text
