name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh .github/scripts/teams_notification.sh
        env:
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/tag/${GITHUB_REF##*/v}
          RELEASE_TITLE: LFET Maven Plugin Release
          RELEASE_TEXT: "Release: ${{github.event.ref }}"