name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sh .github/scripts/teams_notification.sh